version: "3.9"

services:
  mysql_team_management:
    image: mysql
    container_name: mysql_team_management
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: team_management
      MYSQL_USER: team_management
      MYSQL_ROOT_PASSWORD: team_management
      MYSQL_PASSWORD: team_management
    volumes:
      - team_management_volume:/var/lib/mysql
    restart: always
  team_service:
    build:
      context: ./team
    ports:
      - '50003:50003'
    restart: always
    depends_on:
      - mysql_team_management
    environment:
      DB_HOST: mysql_team_management
      DB_NAME: team_management
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
    container_name: team_service
    networks:
      - aman_network
  player_service:
    build:
      context: ./player
    ports:
      - '50005:50005'
    restart: always
    depends_on:
      - mysql_team_management
    environment:
      DB_HOST: mysql_team_management
      DB_NAME: team_management
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
    container_name: player_service
    networks:
      - aman_network
  team_manager_service:
    build:
      context: ./team_manager
    volumes:
      - .:/opt/app
    ports:
      - '50007:50007'
    restart: always
    depends_on:
      - mysql_team_management
    environment:
      DB_NAME: team_management
      DB_HOST: mysql_team_management
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
    container_name: team_manager_service
    networks:
      - aman_network
networks:
  aman_network:
    driver: bridge
    external: true
volumes:
  team_management_volume: