version: "3.9"

services:
  mysql_db:
    image: mysql:8.2.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: team_management
      MYSQL_USER: team_management
      MYSQL_ROOT_PASSWORD: team_management
      MYSQL_PASSWORD: team_management
    volumes:
      - team_database:/var/lib/mysql
    restart: always
  team_management:
    build:
      context: ./team
    volumes:
      - .:/opt/app
    ports:
      - '50003:50003'
    restart: always
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
  player_management:
    build:
      context: ./player
    volumes:
      - .:/opt/app
    ports:
      - '50004:50004'
    restart: always
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
