version: "3.9"

services:
  mysql_team_management:
    image: mysql
    container_name: mysql_team_management
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: team_management
      MYSQL_USER: team_management
      MYSQL_ROOT_PASSWORD: team_management
      MYSQL_PASSWORD: team_management
    volumes:
      - /var/lib/mysql
    restart: always
  team_management:
    build:
      context: ./team
    volumes:
      - .:/opt/app
    ports:
      - '50003:50003'
    restart: always
    depends_on:
      - mysql_team_management
    environment:
      DB_HOST: mysql_team_management
      DB_NAME: team_management
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
  player_management:
    build:
      context: ./player
    volumes:
      - .:/opt/app
    ports:
      - '50005:50005'
    restart: always
    depends_on:
      - mysql_team_management
    environment:
      DB_HOST: mysql_team_management
      DB_NAME: team_management
      DB_USERNAME: team_management
      DB_PASSWORD: team_management
  teamManager_management:
    build:
      context: ./teamManager
    volumes:
      - .:/opt/app
    ports:
      - '50007:50007'
    restart: always
    depends_on:
      - mysql_team_management
    environment:
      DB_NAME: team_management
      DB_HOST: mysql_team_management
      DB_USERNAME: team_management
      DB_PASSWORD: team_management