# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: player.proto for package 'player'

require 'grpc'
require_relative 'player_pb'

module Player
  module Player
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'player.Player'

      rpc :GetPlayer, ::Player::GetPlayerRequest, ::Player::GetPlayerResponse
      rpc :CreatePlayer, ::Player::CreatePlayerRequest, ::Player::CreatePlayerResponse
      rpc :UpdatePlayer, ::Player::UpdatePlayerRequest, ::Player::UpdatePlayerResponse
      rpc :DeletePlayer, ::Player::DeletePlayerRequest, ::Player::DeletePlayerResponse
      rpc :GetPlayers, ::Player::GetPlayersRequest, ::Player::GetPlayersResponse
      rpc :GetOffersByPlayer, ::Player::GetOffersByPlayerRequest, ::Player::GetOffersByPlayerResponse
      rpc :GetRecommendedOffer, ::Player::GetPlayerRequest, ::Offer::OfferItem
    end

    Stub = Service.rpc_stub_class
  end
end
