# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: teamManager.proto for package 'teamManager'

require 'grpc'
require_relative 'teamManager_pb'

module TeamManager
  module TeamManager
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'teamManager.TeamManager'

      rpc :GetTeamManager, ::TeamManager::GetTeamManagerRequest, ::TeamManager::GetTeamManagerResponse
      rpc :GetTeamManagers, ::TeamManager::GetTeamManagersRequest, ::TeamManager::GetTeamManagersResponse
      rpc :CreateTeamManager, ::TeamManager::CreateTeamManagerRequest, ::TeamManager::CreateTeamManagerResponse
      rpc :UpdateTeamManager, ::TeamManager::UpdateTeamManagerRequest, ::TeamManager::UpdateTeamManagerResponse
      rpc :DeleteTeamManager, ::TeamManager::DeleteTeamManagerRequest, ::TeamManager::DeleteTeamManagerResponse
    end

    Stub = Service.rpc_stub_class
  end
end
