# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in Team_Management.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'minitest', '~> 5.16'

gem 'grpc', '~> 1.32'

gem 'rubocop', group: 'development', require: false

gem 'activerecord', '~> 6.1.4'

gem 'mysql2', '>= 0.4.4', '< 0.6.0'

gem 'test-unit', '~> 3.3', '>= 3.3.5'

gem 'grpc-tools', '~> 1.32'
