# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: PlayerManagement.proto for package 'PlayerManagement'

require 'grpc'
require 'PlayerManagement_pb'

module PlayerManagement
  module PlayerManagementService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'PlayerManagement.PlayerManagementService'

      rpc :GetPlayer, ::PlayerManagement::GetPlayerRequest, ::PlayerManagement::GetPlayerResponse
      rpc :CreatePlayer, ::PlayerManagement::CreatePlayerRequest, ::PlayerManagement::CreatePlayerResponse
      rpc :UpdatePlayer, ::PlayerManagement::UpdatePlayerRequest, ::PlayerManagement::UpdatePlayerResponse
      rpc :DeletePlayer, ::PlayerManagement::DeletePlayerRequest, ::PlayerManagement::DeletePlayerResponse
      rpc :GetPlayers, ::PlayerManagement::GetPlayersRequest, ::PlayerManagement::GetPlayersResponse
    end

    Stub = Service.rpc_stub_class
  end
end
