# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: TeamManagement.proto for package 'Team_Management'

require 'grpc'
require 'TeamManagement_pb'

module TeamManagement
  module TeamManagement
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Team_Management.TeamManagement'

      rpc :CreateTeam, ::TeamManagement::CreateTeamRequest, ::TeamManagement::CreateTeamResponse
      rpc :GetTeam, ::TeamManagement::GetTeamRequest, ::TeamManagement::GetTeamResponse
      rpc :UpdateTeam, ::TeamManagement::UpdateTeamRequest, ::TeamManagement::UpdateTeamResponse
      rpc :DeleteTeam, ::TeamManagement::DeleteTeamRequest, ::TeamManagement::DeleteTeamResponse
      rpc :GetTeams, ::TeamManagement::GetTeamsRequest, ::TeamManagement::GetTeamsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
